AWSTemplateFormatVersion: "2010-09-09"

Resources:
  Table:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: WorkEmail
          AttributeType: S
        - AttributeName: CertificationName
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: WorkEmail
          KeyType: HASH
        - AttributeName: CertificationName
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: false
      TableName: AWSCertifications